networks: 
  testnetwork:
    driver: bridge

services:
  demodockercomposeintro:
    image: ${DOCKER_REGISTRY-}demodockercomposeintro
    build:
      context: .
      dockerfile: DemoDockerComposeIntro/Dockerfile
    networks: 
      - testnetwork
    ports:
      - 8080:8080


  demodockercomposebase:
    image: hello-world
    ports:
    - 8081:8081
    networks: 
      - testnetwork
    depends_on:
      - demodockercomposeintro
