volumes:
  sqlvolume:
networks:
 demonetwork:
  driver: bridge

services:
  demodockercomposeapi-db:
    image: ${DOCKER_REGISTRY-}demodockercomposeapidb
    build:
      context: .
      dockerfile: DemoDockerComposeAPI-DB/Dockerfile
    networks:
      - demonetwork
    ports:
    - 8001:8080
    depends_on:
    - demodb


  demodb:
    container_name: demodb
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
    - 8002:1433
    networks:
      - demonetwork
    volumes:
    - sqlvolume:/var/opt/mssql
    environment: 
      SA_PASSWORD: "Test1234!"
      ACCEPT_EULA: "Y"